# Generated by Django 3.1 on 2020-08-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
