# Generated by Django 3.1 on 2020-08-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostapp', '0002_post_total_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
